// Input:  An Integer n;

// Goal: return a string that is generated by following rules:
// n = 1.     1
// n = 2.     11 because 1 is read off as "one 1" or 11
// n = 3.     21 because 11 is read off as "two 1s" or 21.
// n = 4.     1211 because 21 is read off as "one 2, then one 1" or 1211.
// n = 5.     111221
//
// Output: A String;
//
// Example: Input: 4   Output: "1211"
//
// Company: Facebook

import java.util.Arrays;

public class CountAndSay {
    public String countAndSay(int n) {
        String result = "1";

        for (int i = 2; i <= n; i++) {
            // generate new string for next level;
            result = generateString(result);
        }
        return result;
    }

    private String generateString(String s) {
        StringBuilder sb = new StringBuilder();

        char[] charArray = s.toCharArray();
        char current = charArray[0];
        int count = 1;

        for (int i = 1; i < charArray.length; i++) {
            if (current == charArray[i]) {
                count++;
            } else {
                sb.append(count);
                sb.append(current);

                count = 1;
                current = charArray[i];
            }
        }

        // Do not forget to append last count and value to the string.
        sb.append(count);
        sb.append(current);

        return sb.toString();
    }

    public static void main(String[] args) {
        CountAndSay c = new CountAndSay();
        System.out.println(c.countAndSay(4));
    }
}
